### ISSUE TITLE
ASCII only?

### ISSUE THREAD

**Issue by vyo** [kneufeld/consolemd#1]
Hey there, is this supposed to work for ASCII-encoded files only? I'm getting an error on trying to render a Markdown file with UTF contents.

I'm on macOS Sierra here, and installed via `pip install consolemd`, with both `pip` and `python` courtesy of `brew`.

```sh
/usr/local/lib/python2.7/site-packages/CommonMark/blocks.py:677: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if c == '\t':
Traceback (most recent call last):
  File "/usr/local/bin/consolemd", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/consolemd/cli.py", line 86, in cli
    renderer.render( md, **kw )
  File "/usr/local/lib/python2.7/site-packages/consolemd/renderer.py", line 49, in render
    ast = self.parser.parse( md )
  File "/usr/local/lib/python2.7/site-packages/CommonMark/blocks.py", line 893, in parse
    self.incorporate_line(lines[i])
  File "/usr/local/lib/python2.7/site-packages/CommonMark/blocks.py", line 841, in incorporate_line
    self.add_line()
  File "/usr/local/lib/python2.7/site-packages/CommonMark/blocks.py", line 605, in add_line
    self.tip.string_content += (self.current_line[self.offset:] + '\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 40: ordinal not in range(128)
```

**Comment by kneufeld** [comment]
I see the problem and have a fix. I'm at work now so I'll push a new version tonight or tomorrow evening.

You have the honor of being my first official bug report on github. My thanks for checking out consolemd and taking the time to bring this to my attention.

**Comment by vyo** [comment]
Don't sweat it, I'll have a look once it's ready.

**Comment by kneufeld** [comment]
A `pip install -U consolemd` should sort you out. Thanks for the bug report.

**Comment by vyo** [comment]
Works like a charm, thanks a bunch!
